<a href="https://colab.research.google.com/github/Kumaresh7604/Kumaresh-ML/blob/numpy/Daily%20Work%20Ex5%20(18.02.26).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [102]:
#Daily Exercise of Student DB
#Numpy Exercise 5
import numpy as np
np.random.seed(50)
marks = np.random.randint(10, 101,size =(10,5))
print(marks)

[[ 58  21  43  14  80]
 [ 80  32  15  12  81]
 [ 78  88  45  36 100]
 [ 16  30  53  41  59]
 [ 95  51  74  16  29]
 [ 12  89  40  45  36]
 [ 70  76  86  77  12]
 [ 20  61  10  10  21]
 [ 40  36  81  61  38]
 [ 34  56  72  23  81]]


In [103]:
average_by_sub = np.mean(marks,axis=0)
print("Average =",average_by_sub)
Highest_mark_by_sub = np.max(marks,axis=0)
print("Highest Mark per Sub =", Highest_mark_by_sub)
Lowest_mark_by_sub = np.min(marks,axis=0)
print("Lowest Mark per Sub =", Lowest_mark_by_sub)

Average = [50.3 54.  51.9 33.5 53.7]
Highest Mark per Sub = [ 95  89  86  77 100]
Lowest Mark per Sub = [12 21 10 10 12]


In [104]:
Class_Topper = np.sum(marks,axis = 1)
print("The Topper of the Class is",np.argmax(Class_Topper),"with highest total of",np.max(Class_Topper),"out of 500")

The Topper of the Class is 2 with highest total of 347 out of 500


In [105]:
Pass_Sub = marks>35
print(Pass_Sub)
Pass_count = np.sum(Pass_Sub, axis = 0)
print(Pass_count)

[[ True False  True False  True]
 [ True False False False  True]
 [ True  True  True  True  True]
 [False False  True  True  True]
 [ True  True  True False False]
 [False  True  True  True  True]
 [ True  True  True  True False]
 [False  True False False False]
 [ True  True  True  True  True]
 [False  True  True False  True]]
[6 7 8 5 7]


In [106]:
difficult = np.argmin(Pass_count)
print(difficult)
Lowest_Avg = np.min(average_by_sub)
print(np.min(average_by_sub))

3
33.5


In [107]:
ranking= np.sum(marks,axis=1)
print(ranking)
print(np.argsort(-ranking))

[216 220 347 199 265 222 321 122 256 266]
[2 6 9 4 8 5 1 0 3 7]
