<a href="https://colab.research.google.com/github/Kumaresh7604/Kumaresh-ML/blob/numpy/NumpyEx2%2C3%2C4(17.02.26).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy exercise 2
import numpy as np
arr = np.array([12.5, 15.2, 14.8, 13.5, 16.0, 17.1, 15.6])
print(arr)

[12.5 15.2 14.8 13.5 16.  17.1 15.6]


In [ ]:
total = np.sum(arr)
average = np.mean(arr)
print(total)
print(average)

104.69999999999999
14.957142857142856


In [ ]:
minimum = np.min(arr)
maximum = np.max(arr)
diff = np.diff(arr)
print(
    "Minimum Temp : \n", minimum,
    "\n Maximum Temp : \n",maximum,
    "\n Difference between temperature every day : \n", diff
)

Minimum Temp : 
 12.5 
 Maximum Temp : 
 17.1 
 Difference between temperature every day : 
 [ 2.7 -0.4 -1.3  2.5  1.1 -1.5]


In [ ]:
print(arr[arr>16])

[17.1]


In [ ]:
#numpy exercise 3
import numpy as np
marks = np.array([85, 90, 78, 88, 92])
Highest = np.max(marks)
Lowest = np.min(marks)
Average = np.mean(marks)
print(Highest,Lowest,Average)


92 78 86.6


In [ ]:
difference = marks - Average
print(difference)

[-1.6  3.4 -8.6  1.4  5.4]


In [ ]:
percentage = marks.astype(float)
print(percentage)

[85. 90. 78. 88. 92.]


In [ ]:
find = marks[marks>80]
print(find)

[85 90 88 92]


In [ ]:
#numpy exercise 4
import numpy as np
stock = np.array([102.5, 104.2, 101.8, 103.0, 105.5, 107.3])
print(stock)
print(" Maximum = ", np.max(stock),"\n",
      "Minimum = ", np.min(stock),"\n",
      "Average = ", np.mean(stock)
)

[102.5 104.2 101.8 103.  105.5 107.3]
 Maximum =  107.3 
 Minimum =  101.8 
 Average =  104.05


In [ ]:
diff = np.diff(stock)
print(diff)

[ 1.7 -2.4  1.2  2.5  1.8]


In [ ]:
percentage_change = (diff / stock[:-1]) * 100
percentage_change = np.round(percentage_change, 2)
print(percentage_change)
increased = percentage_change[percentage_change>1.5]
print(increased)

[ 1.66 -2.3   1.18  2.43  1.71]
[1.66 2.43 1.71]
